import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { RolePermissionsWhereInputObjectSchema as RolePermissionsWhereInputObjectSchema } from './objects/RolePermissionsWhereInput.schema';
import { RolePermissionsOrderByWithAggregationInputObjectSchema as RolePermissionsOrderByWithAggregationInputObjectSchema } from './objects/RolePermissionsOrderByWithAggregationInput.schema';
import { RolePermissionsScalarWhereWithAggregatesInputObjectSchema as RolePermissionsScalarWhereWithAggregatesInputObjectSchema } from './objects/RolePermissionsScalarWhereWithAggregatesInput.schema';
import { RolePermissionsScalarFieldEnumSchema } from './enums/RolePermissionsScalarFieldEnum.schema';
import { RolePermissionsCountAggregateInputObjectSchema as RolePermissionsCountAggregateInputObjectSchema } from './objects/RolePermissionsCountAggregateInput.schema';
import { RolePermissionsMinAggregateInputObjectSchema as RolePermissionsMinAggregateInputObjectSchema } from './objects/RolePermissionsMinAggregateInput.schema';
import { RolePermissionsMaxAggregateInputObjectSchema as RolePermissionsMaxAggregateInputObjectSchema } from './objects/RolePermissionsMaxAggregateInput.schema';
import { RolePermissionsAvgAggregateInputObjectSchema as RolePermissionsAvgAggregateInputObjectSchema } from './objects/RolePermissionsAvgAggregateInput.schema';
import { RolePermissionsSumAggregateInputObjectSchema as RolePermissionsSumAggregateInputObjectSchema } from './objects/RolePermissionsSumAggregateInput.schema';

export const RolePermissionsGroupBySchema: z.ZodType<Prisma.RolePermissionsGroupByArgs> = z.object({ where: RolePermissionsWhereInputObjectSchema.optional(), orderBy: z.union([RolePermissionsOrderByWithAggregationInputObjectSchema, RolePermissionsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: RolePermissionsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RolePermissionsScalarFieldEnumSchema), _count: z.union([ z.literal(true), RolePermissionsCountAggregateInputObjectSchema ]).optional(), _min: RolePermissionsMinAggregateInputObjectSchema.optional(), _max: RolePermissionsMaxAggregateInputObjectSchema.optional(), _avg: RolePermissionsAvgAggregateInputObjectSchema.optional(), _sum: RolePermissionsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.RolePermissionsGroupByArgs>;

export const RolePermissionsGroupByZodSchema = z.object({ where: RolePermissionsWhereInputObjectSchema.optional(), orderBy: z.union([RolePermissionsOrderByWithAggregationInputObjectSchema, RolePermissionsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: RolePermissionsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RolePermissionsScalarFieldEnumSchema), _count: z.union([ z.literal(true), RolePermissionsCountAggregateInputObjectSchema ]).optional(), _min: RolePermissionsMinAggregateInputObjectSchema.optional(), _max: RolePermissionsMaxAggregateInputObjectSchema.optional(), _avg: RolePermissionsAvgAggregateInputObjectSchema.optional(), _sum: RolePermissionsSumAggregateInputObjectSchema.optional() }).strict();